### ISSUE TITLE
[Bug]: can't create new model from ckpt 

### ISSUE THREAD

**Issue by lilyzlt** [d8ahazard/sd_dreambooth_extension#1379]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### What happened?

create new model from old models(.ckpt),get error
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/15058321/88e4a7ad-0730-4307-a525-09b01e000752)

### Command Line Arguments

```Shell
python launch.py --enable-insecure-extension-access --api --deepdanbooru --listen --port 52369
```

### Console logs

```Shell
result = extract_checkpoint(new_model_name=new_model_name,
  File "/data/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 151, in extract_checkpoint
    original_config_file = get_config_file(train_unfrozen, model_type)
  File "/data/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/sd_to_diff.py", line 82, in get_config_file
    model_version_name = model_versions[model_type]
KeyError: ''

Traceback (most recent call last):
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/gradio/blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 10, received: 3).
Wanted outputs:
    [dropdown, html, html, html, html, html, html, html, slider, html]
Received outputs:
    [None, "", "<div class='error'>KeyError: &#x27;&#x27;</div>"]
Error completing request
Arguments: ('vtest', 'novelAI.ckpt [a7529df023]', '', False, '', '', False, False, '') {}
```

**Comment by mostafahazim** [comment]
Facing the same issue

**Comment by d8ahazard** [comment]
Please try the dev branch, this should be resolved.

**Comment by mostafahazim** [comment]
@d8ahazard  thanks working fine on dev branch

**Comment by d8ahazard** [comment]
Closed as changes are added to main.

**Comment by lilyzlt** [comment]
still the same
![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/15058321/ff48c7ad-76dc-4056-b747-a29a1a49941f)

![image](https://github.com/d8ahazard/sd_dreambooth_extension/assets/15058321/3820d6c8-572f-4aec-b259-02d3f16ad1dd)
