### ISSUE TITLE
Model Revision: Error - tuple index out of error

### ISSUE THREAD

**Issue by HoneyCodeBadger** [d8ahazard/sd_dreambooth_extension#343]
Hi, 

useing the standard params and the wizard (first shot for me) run straight into an error. 
I already tried to play arround with the parameter, but it's always the same.

```
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/0.0GB
 Reserved: 0.0/0.0GB

Replace CrossAttention.forward to use default
Error completing request
Arguments: ('JohnDoe',) {}
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\User\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 598, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 491, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 456, in main
    accelerator = Accelerator(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 285, in __init__
    self.state = AcceleratorState(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\accelerate\state.py", line 69, in __init__
    self._check_initialized(mixed_precision, cpu)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\accelerate\state.py", line 268, in _check_initialized
    raise ValueError(err.format(flag=f"mixed_precision='{mixed_precision}'"))
ValueError: AcceleratorState has already been initialized and cannot be changed, restart your runtime completely and pass `mixed_precision='fp16'` to `Accelerate()`.

Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```

That's my setup:
```

venv "C:\Users\User\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 98947d173e3f1667eba29c904f681047dea9de90
Installing requirements for Web UI
[auto-sd-paint-ext] Attempting auto-update...
[auto-sd-paint-ext] Fetch upstream.
[auto-sd-paint-ext] Pull upstream.


Checking Dreambooth requirements...
Checking/upgrading existing torch/torchvision installation
Checking torch and torchvision versions
Dreambooth revision is a66a2d6bca536207ca3154324f73a5cd43a65cb4
[X] bitsandbytes version 0.35.0 installed.
[X] diffusers version 0.8.1 installed.
[X] transformers version 4.21.0 installed.
[X] torch version 1.12.1+cu116 installed.
[X] torchvision version 0.13.1+cu116 installed.
[*] xformers version 0.0.14.dev0 installed.

Launching Web UI with arguments: --xformers --api
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Loading weights [a9263745] from C:\Users\User\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Global Step: 840000
Applying xformers cross attention optimization.
Model loaded.
Loaded a total of 1 textual inversion embeddings.
Embeddings: John Doe
Running on local URL:  http://127.0.0.1:7860
```

**Comment by zakinp** [comment]
I got this error too, the version of webui and dreambooth extension are all up-to-date.

**Comment by zark119** [comment]
same here. I have 3060 12gb card.

**Comment by ethansmith2000** [comment]
I got it as well, to note i was using class prompt and it occurred while generating class images, on 512x512 model

**Comment by 9121991** [comment]
same here, I got the error when I clicked train. I then installed a new anaconda environment + fresh install of automatic's UI + dreambooth extension. Now I can't even create a new model, it brings up the same error

**Comment by chakalakasp** [comment]
I get this error if I allow 8 bit Adam and mixed precision (fp16) to be used.  This is the setting the performance optimizer suggests (which is kinda silly, I have a 3090, it can run everything fine without mixed precision).

**Comment by illumnat** [comment]
Getting the same. Running on an A4000 at RunPod.io.

**Comment by d8ahazard** [comment]
Resolved with 1913bc7

**Comment by chakalakasp** [comment]
This issue seems to be related to switching the mixed precision mode after already loading the Dreambooth code - when you do this it warns you in the command terminal that you cleave to restart Dreambooth for this to work. Easiest way to self-fix it is to close out your stable diffusion instance (you can leave the web browser open), re-run the stable diffusion launcher bat file, and then try training again. Maybe future code will allow it to auto restart itself to avoid this

**Comment by mpatzner** [comment]
> However mixed precision fp16 and bf16 both don't work and give the _tuple index out of range_ error.

I can confirm (on a Mac M1 Pro), both fp16 and bf16 give the _tuple index out of range_ error. Training does work but does not use any GPU at all.

```
(web-ui) ➜  stable-diffusion-webui git:(master) ✗ ./run_webui_mac.sh
WARNING: overwriting environment variables set in the machine
overwriting variable PYTORCH_ENABLE_MPS_FALLBACK
To make your changes take effect please reactivate your environment
WARNING: overwriting environment variables set in the machine
overwriting variable PYTORCH_ENABLE_MPS_FALLBACK
Already up to date.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Patching transformers to fix kwargs errors.
Dreambooth API layer loaded
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7460a6fa] from /Users/mapali/Sites/automatic1111/stable-diffusion-webui/models/Stable-diffusion/sd-v1-4.ckpt
Applying cross attention optimization (InvokeAI).
Model loaded.
Loaded a total of 1 textual inversion embeddings.
Embeddings: .pt
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

Replace CrossAttention.forward to use FlashAttention
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Loaded model.
 Allocated: 0.0GB
 Reserved: 0.0GB


===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
WARNING: No libcudart.so found! Install CUDA or the cudatoolkit package (anaconda)!
CUDA SETUP: Loading binary /Users/mapali/miniconda/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so...
Exception importing 8bit adam: dlopen(/Users/mapali/miniconda/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so, 0x0006): tried: '/Users/mapali/miniconda/envs/web-ui/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cpu.so' (not a mach-o file)
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Scheduler, EMA Loaded.
 Allocated: 0.0GB
 Reserved: 0.0GB

***** Running training *****
  Num examples = 9
  Num batches each epoch = 9
  Num Epochs = 45
  Instantaneous batch size per device = 1
  Total train batch size (w. parallel, distributed & accumulation) = 1
  Gradient Accumulation steps = 1
  Total optimization steps = 400
   Training settings: CPU: False Adam: False, Prec: no, Grad: True, TextTr: False EM: False, LR: 1e-06
 Allocated: 0.0GB
 Reserved: 0.0GB

Steps:   1%|██                                                                                                                                                              | 5/400 [01:55<2:29:13, 22.67s/it, loss=0.268, lr=1e-6, vram=0.0/0.0GB] Step 5 completed.
```

**Comment by HoneyCodeBadger** [comment]
I can do, whatever I want. Tried with 8bit Adam and without (restart) included. The tuple error remains. @d8ahazard might you reopen the issue request? :)
```
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Replace CrossAttention.forward to use default
Error completing request
Arguments: ('JoJdl', False) {}
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\User\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 506, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 504, in main
    vae=AutoencoderKL.from_pretrained(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\diffusers\modeling_utils.py", line 388, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\User\stable-diffusion-webui\models\dreambooth\JoJdl\working.

Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/0.0GB
 Reserved: 0.0/0.0GB

Replace CrossAttention.forward to use xformers
Error completing request
Arguments: ('JoJdl', False) {}
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\User\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 506, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 464, in main
    accelerator = Accelerator(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\accelerate\accelerator.py", line 285, in __init__
    self.state = AcceleratorState(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\accelerate\state.py", line 69, in __init__
    self._check_initialized(mixed_precision, cpu)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\accelerate\state.py", line 268, in _check_initialized
    raise ValueError(err.format(flag=f"mixed_precision='{mixed_precision}'"))
ValueError: AcceleratorState has already been initialized and cannot be changed, restart your runtime completely and pass `mixed_precision='fp16'` to `Accelerate()`.

Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```
+ + + restart + + +
```
Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.0GB

Replace CrossAttention.forward to use xformers
Error completing request
Arguments: ('JoJdl', False) {}
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\User\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 506, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 504, in main
    vae=AutoencoderKL.from_pretrained(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\diffusers\modeling_utils.py", line 388, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\User\stable-diffusion-webui\models\dreambooth\JoJdl\working.

Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
Extracting checkpoint...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/0.0GB
 Reserved: 0.0/0.0GB

Exception with the conversion: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.17 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 862, in extract_checkpoint
    checkpoint = torch.load(checkpoint_info[0], map_location=map_location)["state_dict"]
  File "C:\Users\User\stable-diffusion-webui\modules\safe.py", line 102, in load
    return load_with_extra(filename, *args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\modules\safe.py", line 147, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 712, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1049, in _load
    result = unpickler.load()
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1019, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 1001, in load_tensor
    wrap_storage=restore_location(storage, location),
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 973, in restore_location
    return default_restore_location(storage, str(map_location))
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\serialization.py", line 157, in _cuda_deserialize
    return obj.cuda(device)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\torch\_utils.py", line 78, in _cuda
    return torch._UntypedStorage(self.size(), device=torch.device('cuda')).copy_(self, non_blocking)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 8.00 GiB total capacity; 7.17 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Unable to find working dir, extraction likely failed: feature_extractor
Unable to find working dir, extraction likely failed: safety_checker
Unable to find working dir, extraction likely failed: scheduler
Unable to find working dir, extraction likely failed: text_encoder
Unable to find working dir, extraction likely failed: tokenizer
Unable to find working dir, extraction likely failed: unet
Unable to find working dir, extraction likely failed: vae
Extraction failed, removing model directory.
 Restored system models.
 Allocated: 2.0GB
 Reserved: 7.3GB

 Allocated 2.0/7.2GB
 Reserved: 7.3/7.3GB

Starting Dreambooth training...
 Cleanup completed.
 Allocated: 0.0GB
 Reserved: 0.0GB

 Allocated 0.0/2.0GB
 Reserved: 0.0/2.3GB

Replace CrossAttention.forward to use xformers
Error completing request
Arguments: ('JoJdl', False) {}
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\modules\ui.py", line 185, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\User\stable-diffusion-webui\webui.py", line 54, in f
    res = func(*args, **kwargs)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 506, in start_training
    config, mem_record = main(config, mem_record)
  File "C:\Users\User\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 504, in main
    vae=AutoencoderKL.from_pretrained(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\diffusers\modeling_utils.py", line 388, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named diffusion_pytorch_model.bin found in directory C:\Users\User\stable-diffusion-webui\models\dreambooth\JoJdl\working.

Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 284, in run_predict
    output = await app.blocks.process_api(
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 983, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\User\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 913, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range
```

**Comment by cass02** [comment]
@HoneyCodeBadger I had this error as well; however, when I switched from "safetensors" to "ckpt", it started to work again.

**Comment by alenknight** [comment]
> @HoneyCodeBadger I had this error as well; however, after switching models, it started to work again (I switched from a "safetensors" model to a "ckpt" one).

THIS!  i had a heck of a time tonight trying to figure this out... i just went and converted all my stuff to safetensors... cause ya know... supposed to be better... and none of my training was working... .then ... on a whim, i tried to use a ckpt file... bam worked.  ugh.
