### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by javieranguloluna** [d8ahazard/sd_dreambooth_extension#824]
After install with the automatic1111 ui and relaunch a1111 y get this error:

Settings file found, loading
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Updating Settings File
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Launcher Version 1.5.8
 i   Launching without args
 i   Python 3.10 path found : C:\Users\Usuario\AppData\Local\Programs\Python\Python310\python.exe
 i   Python is in PATH
 i   Git found at C:\Program Files\Git
 i   Git is in PATH
 i   Automatic1111 SD WebUI found at C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Opening A1111 WebUI Launcher
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers
 i   Enable Xformers updated to True
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Updating Settings File
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers --xformers
 i   Additional Args updated
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 →   Updating Settings File
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Webui
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 ↺   Updating Extension: sd_dreambooth_extension
 ✓   SUCCESS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 i   Arguments are now: --xformers
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  WEBUI LAUNCHING VIA EMS LAUNCHER, EXIT THIS WINDOW TO STOP THE WEBUI
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 !   Any error happening after 'commit hash : XXXX' is not related to the launcher. Please report them on Automatic1111's github instead :
 ☁   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/new/choose
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Cancel
venv "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: c98cb0f8ecc904666f47684e238dd022039ca16f
Installing requirements for Web UI
Error running install.py for extension extensions\sd_dreambooth_extension.
Command: "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" "extensions\sd_dreambooth_extension\install.py"
Error code: 1
stdout:
#######################################################################################################
Initializing Dreambooth
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Dreambooth revision: e693070d62885313e67cb49dabe4fa5a510b36a6
SD-WebUI revision: c98cb0f8ecc904666f47684e238dd022039ca16f

Checking Dreambooth requirements...

stderr: Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 90, in <module>
    run(f'"{sys.executable}" -m pip install -r "{req_file}"', f"Checking {name} requirements...",
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 65, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment
Collecting accelerate==0.15.0
  Using cached accelerate-0.15.0-py3-none-any.whl (191 kB)
Requirement already satisfied: albumentations==1.3.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: bitsandbytes==0.35.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 3)) (0.35.0)
Requirement already satisfied: diffusers==0.10.2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.10.2)
Requirement already satisfied: fastapi==0.87.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (0.87.0)
Requirement already satisfied: ftfy==6.1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (6.1.1)
Requirement already satisfied: modelcards==0.1.6 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (0.1.6)
Requirement already satisfied: tensorboard==2.11.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.11.0)
Collecting tensorflow==2.11.0
  Using cached tensorflow-2.11.0-cp310-cp310-win_amd64.whl (1.9 kB)
Requirement already satisfied: tqdm==4.64.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (4.64.1)
Collecting transformers==4.25.1
  Using cached transformers-4.25.1-py3-none-any.whl (5.8 MB)
Requirement already satisfied: discord-webhook==1.0.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from -r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 13)) (1.0.0)
Requirement already satisfied: numpy>=1.17 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.23.3)
Requirement already satisfied: torch>=1.4.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (1.12.1+cu113)
Requirement already satisfied: psutil in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (5.9.4)
Requirement already satisfied: pyyaml in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (6.0)
Requirement already satisfied: packaging>=20.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from accelerate==0.15.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 1)) (23.0)
Requirement already satisfied: scipy in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.10.0)
Requirement already satisfied: scikit-image>=0.16.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.19.2)
Requirement already satisfied: qudida>=0.0.4 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (0.0.4)
Requirement already satisfied: opencv-python-headless>=4.1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (4.7.0.68)
Requirement already satisfied: filelock in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.9.0)
Requirement already satisfied: Pillow in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (9.4.0)
Requirement already satisfied: importlib-metadata in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (6.0.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.10.31)
Requirement already satisfied: requests in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.25.1)
Requirement already satisfied: huggingface-hub>=0.10.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (0.11.1)
Requirement already satisfied: pydantic!=1.7,!=1.7.1,!=1.7.2,!=1.7.3,!=1.8,!=1.8.1,<2.0.0,>=1.6.2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from fastapi==0.87.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.10.4)
Requirement already satisfied: starlette==0.21.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from fastapi==0.87.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (0.21.0)
Requirement already satisfied: wcwidth>=0.2.5 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from ftfy==6.1.1->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 6)) (0.2.6)
Requirement already satisfied: Jinja2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from modelcards==0.1.6->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 7)) (3.1.2)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.4.6)
Requirement already satisfied: protobuf<4,>=3.9.2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.19.6)
Requirement already satisfied: wheel>=0.26 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.38.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.4.1)
Requirement already satisfied: absl-py>=0.4 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.4.0)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.2.2)
Requirement already satisfied: grpcio>=1.24.3 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.51.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.6.1)
Requirement already satisfied: google-auth<3,>=1.6.3 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.16.0)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.8.1)
Requirement already satisfied: setuptools>=41.0.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (63.2.0)
Collecting tensorflow-intel==2.11.0
  Using cached tensorflow_intel-2.11.0-cp310-cp310-win_amd64.whl (266.3 MB)
Requirement already satisfied: colorama in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tqdm==4.64.1->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 11)) (0.4.6)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from transformers==4.25.1->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 12)) (0.12.1)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Requirement already satisfied: anyio<5,>=3.4.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from starlette==0.21.0->fastapi==0.87.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (3.6.2)
Requirement already satisfied: h5py>=2.9.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.7.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.14.1)
Requirement already satisfied: google-pasta>=0.1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (15.0.6.1)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.6.3)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.30.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.11.0)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.11.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (2.2.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (0.4.0)
Requirement already satisfied: flatbuffers>=2.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (23.1.21)
Requirement already satisfied: opt-einsum>=2.3.2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (4.4.0)
Requirement already satisfied: six>=1.12.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from tensorflow-intel==2.11.0->tensorflow==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 9)) (1.16.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (1.3.1)
Requirement already satisfied: scikit-learn>=0.19.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from qudida>=0.0.4->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (1.26.14)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from requests->diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (2.10)
Requirement already satisfied: imageio>=2.4.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2.24.0)
Requirement already satisfied: PyWavelets>=1.1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.4.1)
Requirement already satisfied: tifffile>=2019.7.26 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (2022.10.10)
Requirement already satisfied: networkx>=2.2 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from scikit-image>=0.16.1->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from werkzeug>=1.0.1->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (2.1.2)
Requirement already satisfied: zipp>=0.5 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from importlib-metadata->diffusers==0.10.2->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 4)) (3.11.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from anyio<5,>=3.4.0->starlette==0.21.0->fastapi==0.87.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 5)) (1.3.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard==2.11.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 8)) (3.2.2)
Requirement already satisfied: joblib>=1.1.1 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages (from scikit-learn>=0.19.1->qudida>=0.0.4->albumentations==1.3.0->-r C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt (line 2)) (3.1.0)
Installing collected packages: requests, accelerate, transformers, tensorflow-intel, tensorflow
  Attempting uninstall: requests
    Found existing installation: requests 2.25.1
    Uninstalling requests-2.25.1:
      Successfully uninstalled requests-2.25.1
  Attempting uninstall: accelerate
    Found existing installation: accelerate 0.12.0
    Uninstalling accelerate-0.12.0:
      Successfully uninstalled accelerate-0.12.0
  Attempting uninstall: transformers
    Found existing installation: transformers 4.19.2
    Uninstalling transformers-4.19.2:
      Successfully uninstalled transformers-4.19.2

stderr: WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
    WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\Usuario\\Documents\\A1111 Web UI Autoinstaller\\stable-diffusion-webui\\venv\\Lib\\site-packages\\tensorflow\\include\\tensorflow\\compiler\\xla\\mlir_hlo\\_virtual_includes\\compose_set_interface_inc_gen\\mlir-hlo\\Dialect\\gml_st\\transforms\\compose_set_interface.h.inc'
HINT: This error might have occurred since this system does not have Windows Long Path support enabled. You can find information on how to enable this at https://pip.pypa.io/warnings/enable-long-paths

WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -rotobuf (c:\users\usuario\documents\a1111 web ui autoinstaller\stable-diffusion-webui\venv\lib\site-packages)

[notice] A new release of pip available: 22.2.1 -> 22.3.1
[notice] To update, run: C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip

Launching Web UI with arguments: --autolaunch --xformers
Error loading script: api.py
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\api.py", line 20, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import from_file, DreamboothConfig
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\dreambooth.py", line 15, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import db_config
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

Error loading script: main.py
Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 6, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import save_config, from_file
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\utils.py", line 23, in <module>
    import tensorflow
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [cc6cb27103] from C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\models\Stable-diffusion\v1-5-pruned-emaonly.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 6.5s (0.4s create model, 3.8s load weights).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by CJohnDesign** [comment]
I was getting 
```
ImportError: cannot import name 'randn_tensor' from 'diffusers.utils'
```

But then I ran this (kinda a hailmary) `!pip install --upgrade diffusers[torch]`

And now I'm getting this error:
```
Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 20, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import from_file, DreamboothConfig
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 23, in <module>
    import tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

Error loading script: dreambooth.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/dreambooth.py", line 15, in <module>
    from extensions.sd_dreambooth_extension.dreambooth import db_config
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 23, in <module>
    import tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

Error loading script: main.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/main.py", line 6, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_config import save_config, from_file
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_config.py", line 9, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.db_concept import Concept
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/db_concept.py", line 7, in <module>
    from extensions.sd_dreambooth_extension.dreambooth.utils import get_images
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/dreambooth/utils.py", line 23, in <module>
    import tensorflow
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python'

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading vocab.json100% 939k/939k [00:00<00:00, 1.87MB/s]
Downloading merges.txt100% 512k/512k [00:00<00:00, 1.23MB/s]
Downloading special_tokens_map.json100% 389/389 [00:00<00:00, 388kB/s]
Downloading tokenizer_config.json100% 905/905 [00:00<00:00, 841kB/s]
Downloading config.json100% 4.41k/4.41k [00:00<00:00, 4.34MB/s]
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 22.8s (5.6s create model, 16.5s load weights).
Running on public URL: https://3b555c4a-3196-4753.gradio.live/
✔ Connected
```

Dreambooth tab does not show up

**Comment by CJohnDesign** [comment]
Update: I fixed with `!pip install tensorflow` right before the start step

**Comment by javieranguloluna** [comment]
I am not familiar with python and pip, can you help me?

**Comment by CJohnDesign** [comment]
For sure, just add a code cell right before the start cell (add button will appear on hover), add that command I pasted above and click play, then click play on the start cell. Should work.

**Comment by javieranguloluna** [comment]
Thanks fou your help but still dont know how. I've the automatic111 installation from Unoficial Unstability team. I have in launcher a cell to put launch params, i've put your pip code there but dont recognise. i've run your pip code in the stable-diffusion-webui folder and installed but when launch, the same error again. What i'm doing wrong??

**Comment by CJohnDesign** [comment]
Oh, I'm using Google Colab. Try removing the ! in front of pip. 

`pip install tensorflow` and you could also try `pip3 install tensorflow`

It's saying it can't find tensorflow so you need to install it

**Comment by javieranguloluna** [comment]
Ok i've installed tensorflow but still get error. I think it is not reading the requirements for instalation and so dont installing it, like tensorflow. i need to install it manually but in the venv, or make it read corectly the requirements??

Checking Dreambooth requirements...

stderr: Traceback (most recent call last):
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 90, in <module>
    run(f'"{sys.executable}" -m pip install -r "{req_file}"', f"Checking {name} requirements...",
  File "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\launch.py", line 65, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install Dreambooth requirements..
Command: "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install -r "C:\Users\Usuario\Documents\A1111 Web UI Autoinstaller\stable-diffusion-webui\extensions\sd_dreambooth_extension\requirements.txt"
Error code: 1
stdout: Ignoring tensorflow-macos: markers 'sys_platform == "darwin" and platform_machine == "arm64"' don't match your environment

**Comment by javieranguloluna** [comment]
Solved! I was running and old or bad configured automatic 1111. I have done a clean reinstall from github oficial repo and now is running well! For some reason the unoficial unstable difusion docs link to an autoinstaller version with old or bad config.

Thanks for the support, hope ussefull for someone else.
