### ISSUE TITLE
ModuleNotFoundError: No module named 'pip install torch==1'

### ISSUE THREAD

**Issue by mykeehu** [d8ahazard/sd_dreambooth_extension#86]
**Have you read the Readme?**
Yes

**Have you completely restarted the stable-diffusion-webUI, not just reloaded the UI?**
Yes

**Have you updated Dreambooth to the latest revision?**
Yes

**Please find the following lines in the console (After "Installing Requirements for WebUI") and paste them below. If you don't see these lines in the console, then update Dreambooth**

`Dreambooth revision is be17dfb014b1f398bc267be9082a69c7856c969c
Diffusers version is 0.8.0.dev0.
Torch version is 1.12.1+cu116.
Torch vision version is 0.13.1+cu116.`

**Describe the bug**
When I start SD, I get this error after the update:

stderr: H:\Stable-Diffusion-Automatic\stable-diffusion-webui\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ' (ModuleNotFoundError: No module named 'pip install torch==1')
Traceback (most recent call last):
  File "H:\Stable-Diffusion-Automatic\stable-diffusion-webui\extensions\sd_dreambooth_extension\install.py", line 14, in <module>
    subprocess.check_call([sys.executable, '-m', torch_cmd])
  File "C:\Users\Mykee\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['H:\\Stable-Diffusion-Automatic\\stable-diffusion-webui\\venv\\Scripts\\python.exe', '-m', 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ']' returned non-zero exit status 1.

**Environment**
What OS?
If Windows - WSL or native? Windows native
What GPU are you using? RTX 3060 12 GB

I switched back to the 182c76fcfd80e58f11aac2e3a6e220c46363758d build to train.

**Comment by YakuzaSuske** [comment]
Just go that too

**Comment by kokakin** [comment]
I'm in the same situation as above but I get a additional error below:
Launching Web UI with arguments:
Error loading script: main.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts
    exec(compiled, module.__dict__)
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in <module>
    from dreambooth import conversion, dreambooth
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in <module>
    from dreambooth.dreambooth import get_db_models
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in <module>
    from dreambooth.train_dreambooth import main
  File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in <module>
    from accelerate import Accelerator
ModuleNotFoundError: No module named 'accelerate'

LatentDiffusion: Running in eps-prediction mode

I did a clean install of everything including python and haven't enabled xformers

**Comment by mykeehu** [comment]
@kokakin Put this line one time in the webui-user.bat file:

`set TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"`

After SD has started, close everything, delete and restart.

**Comment by kokakin** [comment]
> @kokakin Put this line one time in the webui-user.bat file:
> 
> `set TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"`
> 
> After SD has started, close everything, delete this line and restart.

Tried it with the line, then without, then with again and then without again, same error, but before the error there is a ton of "requirements already met". I should mention that the dreambooth tab hasn't appeared after the UI starts.

I hope the issue can be solved :)

**Comment by ShawnOakley** [comment]
Receiving as well.  Above advice had no effect.  Running pip install on requirements.txt says accelerate is successfully installed, but receive same error.

**Comment by xiaolxl** [comment]
> I'm in the same situation as above but I get a additional error below: Launching Web UI with arguments: Error loading script: main.py Traceback (most recent call last): File "C:\stable-diffusion-webui\modules\scripts.py", line 170, in load_scripts exec(compiled, module.**dict**) File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py", line 3, in from dreambooth import conversion, dreambooth File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\conversion.py", line 26, in from dreambooth.dreambooth import get_db_models File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\dreambooth.py", line 10, in from dreambooth.train_dreambooth import main File "C:\stable-diffusion-webui\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 20, in from accelerate import Accelerator ModuleNotFoundError: No module named 'accelerate'
> 
> LatentDiffusion: Running in eps-prediction mode
> 
> I did a clean install of everything including python and haven't enabled xformers

尝试运行pip install accelerate安装

Try running pip install accelerate installation

**Comment by adamdived** [comment]
Ok i solved somehow on Windows, following what @xiaolxl says.

Open Command Prompt and go into your Stabel Diffusion installation directory and type:

`C:\[YOURSTABLEDIFFUSIONPATH]\stable-diffusion-webui\venv\Scripts\python.exe -m pip install accelerate`

This solved at least to me 100%. Now i have the Dreambooth Tab and started training.

**Comment by GhostDragon69** [comment]
@adamdived 
I did run -m pip install accelerate and also set TORCH_COMMAND="pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116"

i wonder what I am doing wrong

i still get this error
D:\AUTOMATIC1111SD\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ' (ModuleNotFoundError: No module named 'pip install torch==1')

I also get this before 

stderr: D:\AUTOMATIC1111SD\venv\Scripts\python.exe: Error while finding module specification for 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ' (ModuleNotFoundError: No module named 'pip install torch==1')
Traceback (most recent call last):
  File "D:\AUTOMATIC1111SD\extensions\sd_dreambooth_extension\install.py", line 14, in <module>
    subprocess.check_call([sys.executable, '-m', torch_cmd])
  File "C:\Users\gtbm1\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['D:\\AUTOMATIC1111SD\\venv\\Scripts\\python.exe', '-m', 'pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 --extra-index-url https://download.pytorch.org/whl/cu116 ']' returned non-zero exit status 1.

**Comment by gmaciocci** [comment]
Getting the same issue since updating today. Yesterday it was working fine

**Comment by toyxyz** [comment]
After disabling the extension, I completely deleted the sd_dreambooth_extension folder and reinstalled it. And the problem was solved.

**Comment by d8ahazard** [comment]
This should be resolved in the latest version(s), as evidenced by the above post.
